account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # previous login view
    #url(r'^login/$', views.user_login, name ='login'),
    # login / logout urls
    url(r'^login/$',
        'django.contrib.auth.views.login',
        name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',{'next_page': '/'},
        name='logout'),
    url(r'^logout-then-login/$',
        'django.contrib.auth.views.logout_then_login',
        name='logout_then_login'),
    url(r'^$', views.dashboard, name='dashboard'),
    # change password urls
    url(r'^password-change/$',
        'django.contrib.auth.views.password_change',
        name='password_change'),
    url(r'^password-change/done/$',
        'django.contrib.auth.views.password_change_done',
        name='password_change_done'),
    # restore password urls
    url(r'^password-reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset'),
    url(r'^password-reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^activate/(?P<key>.+)$', views.activation, name='activation'),
    url(r'^new-activation-link/(?P<user_id>\d+)/$', views.new_activation_link, name='new-activation-link'),

]

bookmarks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'', include('mainpage.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
	url(r'^websites/', include('websites.urls', namespace='websites')),
    url(r'^api/v1/', include('core_apis.urls', namespace='api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^image-edit/(?P<image_id>\d+)/$', views.image_edit, name='image_edit'),
    url(r'^image-delete/(?P<image_id>\d+)/$', views.image_delete, name='image_delete'),
    url(r'^search/$', views.search, name='image-search'),
]

account/models.py
from django.db import models
from django.conf import settings
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)
    activation_key = models.CharField(max_length=40, blank=True, null=True)
    key_expires = models.DateTimeField(blank=True, null=True)

    photo = models.ImageField(upload_to='users/%Y/%m/%d',default='users/default_user_icon/default_user_icon.png',
                                blank=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
    def clean_email(self):
        cd = self.cleaned_data
        email=cd['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
        return email

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from images.models import Image
from articles.models import Article
from videos.models import Video
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib import messages
from social.backends.utils import load_backends
from django.shortcuts import get_object_or_404
from django.utils import timezone
import random
import hashlib
import datetime
from actions.models import Action
from actions.utils import create_action
from .tasks import EmailVerification
from django.contrib.auth.models import User

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated '\
                             'successfully')
        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})


@login_required
def dashboard(request):
    user = request.user
    random_articles = None
    random_videos = None
    random_images = None
    actions = Action.objects.filter(user=user)\
        .prefetch_related('target')
    actions = actions[:10]

    article_ids = list(Article.objects.values_list('id', flat=True).filter(
        user=user))
    video_ids = list(Video.objects.values_list('id', flat=True).filter(
        user=user))
    image_ids = list(Image.objects.values_list('id', flat=True).filter(
        user=user))
    n = 3

    if article_ids and len(article_ids) > 2:
        rand_article_ids = random.sample(article_ids, n)
        random_articles = Article.objects.filter(id__in=rand_article_ids)
    if video_ids and len(video_ids) > 2:
        rand_video_ids = random.sample(video_ids, n)
        random_videos = Video.objects.filter(id__in=rand_video_ids)
    if image_ids and len(image_ids) > 2:
        rand_image_ids = random.sample(image_ids, n)
        random_images = Image.objects.filter(id__in=rand_image_ids)

    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard',
                   'articles': random_articles,
                   'videos': random_videos,
                   'images': random_images,
                   'actions': actions})

def user_login(request):
    if request.method=='POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                               password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.is_active=False
            new_user.save()
            create_action(new_user, 'By: ' + new_user.username, 'Account created', new_user)
            #We generate a random activation key
            salt = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
            usernamesalt = new_user.username
            if isinstance(usernamesalt, str):
                usernamesalt = usernamesalt.encode('utf8')
                usernamesalt = usernamesalt.decode('utf8')

            # Create the user profile
            profile = Profile(user=new_user)
            profile.activation_key= hashlib.sha1((salt+usernamesalt).encode('utf8)')).hexdigest()
            profile.key_expires=str(timezone.localtime(timezone.now()) + timezone.timedelta(days=2))

            profile.save()
            EmailVerification.delay(user_id=new_user.pk)
            return render(request,
                            'account/verification_sent.html',
                            {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                    'account/register.html',
                    {'user_form': user_form})
    # View that handles /already-registered:
#View called from activation email. Activate user if link didn't expire (48h default), or offer to
#send a second link if the first expired.
def activation(request, key):
    activation_expired = False
    already_active = False
    profile = get_object_or_404(Profile, activation_key=key)
    if profile.user.is_active == False:
        if str(timezone.localtime(timezone.now())) > str(profile.key_expires):
            activation_expired = True #Display: offer the user to send a new activation link
            id_user = profile.user.id
            return render(request,
                    'account/new_activation_link.html',
                    {'id_user': id_user})
        else: #Activation successful
            profile.user.is_active = True
            profile.user.save()
    #If user is already active, simply display error message
    else:
        already_active = True #Display : error message
        return render (request, 'already_active.html',
                        {'error': request.GET.get('err')})

    return render(request, 'register_done.html')


def new_activation_link(request, user_id):
    user = User.objects.get(id=user_id)
    profile = user.profile
    if str(timezone.localtime(timezone.now())) < str(profile.key_expires):
        return render(request,
                    'already_sent.html')
    else:
        if user is not None and not user.is_active:
            username=user.username
            salt = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
            usernamesalt = username
            if isinstance(usernamesalt, str):
                usernamesalt = usernamesalt.encode('utf8')
                usernamesalt = usernamesalt.decode('utf8')

            # Create the user profile
            profile.activation_key= hashlib.sha1((salt+usernamesalt).encode('utf8)')).hexdigest()
            profile.key_expires=str(timezone.localtime(timezone.now()) + timezone.timedelta(days=2))

            profile.save()

            EmailVerification.delay(user_id=user.pk)
            return render(request,
                            'account/new_verification_sent.html',
                            {'user': user})

        else:
            return render (request, 'already_active.html',
                              {'error': request.GET.get('err')})


def already_registered(request):
    return render (request, 'already_registered.html',
                              {'error': request.GET.get('err')})

account/templates/already_active.html
{% extends "base.html" %}

{% block title %}Activation{% endblock %}

{% block content %}
    <h1>Already Activated</h1>
    {% if request.user.is_authenticated %}
<p>Your account is already active with MediaShelf and you are currently logged in.
    Thank you for your support.  Enjoy!</p>

    {% else %}
<p>Your account is already active with MediaShelf.  Now you can <a
href="{% url "login" %}">log in</a> here.</p>
{% endif %}
{% endblock %}

account/templates/already_registered.html
{% extends "base.html" %}

{% block title %}You are already registered!{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
<p>Your email is associated with a current account with MediaShelf.
    Please enter your password to complete your sign-in.  You will be automatically
    signed in on future log-in attempts.</p>
<form>
    <label>Username</label> 
    <input name="username" type="text" /> 

     <label>Password</label> 
    <input name="password" type="password" /> 

    <button>Submit</button> 
</form>
{% endblock %}

<!--<form method="post" action="{% url "social:complete" backend %}"> 
        {% if error == 'credentials' %}
            {% endif %} -->
            

account/templates/already_sent.html
{% extends "base.html" %}

{% block title %}Activation{% endblock %}

{% block content %}
    <h1>Activation Key Already Sent</h1>
<p>An activation key has already been sent to you email account.  Please check your email in order to activate this account.  Thanks, from the MediaShelf Team.</p>
{% endblock %}

account/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}


<html>
<head>
    <title>{% block title %}{% endblock %}</title>
	  <link rel="icon" href="{% static "css/icons/media_shelf1.png" %}">
    <link href= "{% static "css/base.css"%}" rel="stylesheet" >
	<link href= "{% static "css/font-awesome-4.7.0/css/font-awesome.min.css"%}" rel="stylesheet">
<link href= "{% static "css/showYtVideo.css"%}" rel="stylesheet" >
<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/amlemnllmhfhldgbdjgekflegjglfcem">
<meta name="viewport" content="width=device-width">
	<meta charset="utf-8" />
</head>
<body>
    <div id="header">
        <div class="header-inner">
        <a href="/">
        <span class="logo"></span>
        </a>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url "dashboard" %}">Home</a>
                </li>
                <li {% if section == "articles" %}class="selected"{% endif %}>
                    <a href="{% url "articles:list" %}">Articles</a>
                </li>

                <li {% if section == "videos" %}class="selected"{% endif %}>
                    <a href="{% url "videos:list" %}">Videos</a>
                </li>
                <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="{% url "images:list" %}">Images</a>
                </li>
                <li {% if section == "websites" %}class="selected"{% endif %}>
                    <a href="{% url "websites:list" %}">Websites</a>
                </li>
                <li {% if section == "howToSave" %}class="selected"{% endif %}>
                    <a href="{% url "howToSave" %}">How to Save</a>
                </li>

            </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
              {% if user.profile.photo %}
                <img src="{{ user.profile.photo.url }}">
                    {% endif %}
                <div class="username">{{ request.user }},</div>
                <a href="{% url "logout" %}">Logout</a>
            {% else %}
                <a href="{% url "login" %}">Log-in</a>
            {% endif %}
        </span>
        <div class="mobile-menu">
            <div class="mobile-icon" id ="drop-down-menu">
              <i class="fa fa-bars fa-2x" aria-hidden="true"></i>
            </div>
          <div class="mobile-icon" id="filter">
            <i class="fa fa-filter fa-2x" aria-hidden="true"></i>
          </div>
        </div>
<br clear="all" />
        </div>
    </div>
    <ul class="dropdown-menu">
        <h2>Menu</h2>
        {% if request.user.is_authenticated %}
        <li {% if section == "dashboard" %}class="selected"{% endif %}>
            <a href="{% url "dashboard" %}">Home</a>
        </li>
        <li {% if section == "articles" %}class="selected"{% endif %}>
            <a href="{% url "articles:list" %}">Articles</a>
        </li>

        <li {% if section == "videos" %}class="selected"{% endif %}>
            <a href="{% url "videos:list" %}">Videos</a>
        </li>
        <li {% if section == "images" %}class="selected"{% endif %}>
            <a href="{% url "images:list" %}">Images</a>
        </li>
        <li {% if section == "websites" %}class="selected"{% endif %}>
            <a href="{% url "websites:list" %}">Websites</a>
        </li>
        <li>
            <a href="{% url "logout" %}">Logout</a>
        </li>
        {% else %}
            <a href="{% url "login" %}">Log-in</a>
        {% endif %}
    </ul>

    <div id="content">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                            <a href="#" class="close">✖</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% block content %}
        {% endblock %}
        <br clear="all" />
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src=" https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
	<script type="text/javascript" src="{% static 'js/main_js.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.showYtVideo.js' %}"></script>
	 <script>var banner_default = "{% static 'css/global_images/mediashelf_banner1.jpg' %}";</script>
<script>
 $(document).ready(function ($) {
            $('.demo').on('click', function () {
                $.showYtVideo({
                    videoId: 'SayaFaahEuc'
                });
            });
        });
</script>
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function(){
            {% block domready %}
 setInterval(function () {
        moveRight();
    }, 8000);

	var slideCount = $('#slider ul li').length;
	var slideWidth = $('#slider ul li').width();
	var slideHeight = $('#slider ul li').height();
	var sliderUlWidth = slideCount * slideWidth;

	$('#slider').css({ width: slideWidth, height: slideHeight });

	$('#slider ul').css({ width: sliderUlWidth, marginLeft: - slideWidth });

    $('#slider ul li:last-child').prependTo('#slider ul');

    function moveLeft() {
        $('#slider ul').animate({
            left: + slideWidth
        }, 200, function () {
            $('#slider ul li:last-child').prependTo('#slider ul');
            $('#slider ul').css('left', '');
        });
    };

    function moveRight() {
        $('#slider ul').animate({
            left: - slideWidth
        }, 500, function () {
            $('#slider ul li:first-child').appendTo('#slider ul');
            $('#slider ul').css('left', '');
        });
    };

    $('a.control_prev').click(function () {
        moveLeft();
    });

    $('a.control_next').click(function () {
        moveRight();
    });
            {% endblock %}
            });
    </script>
<div class="modal-backdrop"></div>
</body>
</html>

account/templates/base2.html
<!DOCTYPE html>
{% load staticfiles %}


<html>
<head>
    <title>{% block title %}{% endblock %}</title>
	  <link rel="icon" href="{% static "css/icons/media_shelf1.png" %}">
    <link href= "{% static "css/base.css"%}" rel="stylesheet" >
	<link href= "{% static "css/font-awesome-4.7.0/css/font-awesome.min.css"%}" rel="stylesheet">
<link href= "{% static "css/showYtVideo.css"%}" rel="stylesheet" >
<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/amlemnllmhfhldgbdjgekflegjglfcem">
<meta name="viewport" content="width=device-width">
	<meta charset="utf-8" />
</head>
<body>
    <div id="header">
        <div class="header-inner">
        <a href="/">
        <span class="logo"></span>
        </a>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url "dashboard" %}">Home</a>
                </li>
                <li {% if section == "articles" %}class="selected"{% endif %}>
                    <a href="{% url "articles:list" %}">Articles</a>
                </li>

                <li {% if section == "videos" %}class="selected"{% endif %}>
                    <a href="{% url "videos:list" %}">Videos</a>
                </li>
                <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="{% url "images:list" %}">Images</a>
                </li>
                <li {% if section == "websites" %}class="selected"{% endif %}>
                    <a href="{% url "websites:list" %}">Websites</a>
                </li>
                <li {% if section == "howToSave" %}class="selected"{% endif %}>
                    <a href="{% url "howToSave" %}">How to Save</a>
                </li>

            </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
              {% if user.profile.photo %}
                <img src="{{ user.profile.photo.url }}">
                    {% endif %}
                <div class="username">{{ request.user }},</div>
                <a href="{% url "logout" %}">Logout</a>
            {% else %}
                <a href="{% url "login" %}">Log-in</a>
            {% endif %}
        </span>
        <div class="mobile-menu">
            <div class="mobile-icon" id ="drop-down-menu">
              <i class="fa fa-bars fa-2x" aria-hidden="true"></i>
            </div>
          <div class="mobile-icon" id="filter">
            <i class="fa fa-filter fa-2x" aria-hidden="true"></i>
          </div>
        </div>
<br clear="all" />
        </div>
    </div>
    <ul class="dropdown-menu">
        <h2>Menu</h2>
        {% if request.user.is_authenticated %}
        <li {% if section == "dashboard" %}class="selected"{% endif %}>
            <a href="{% url "dashboard" %}">Home</a>
        </li>
        <li {% if section == "articles" %}class="selected"{% endif %}>
            <a href="{% url "articles:list" %}">Articles</a>
        </li>

        <li {% if section == "videos" %}class="selected"{% endif %}>
            <a href="{% url "videos:list" %}">Videos</a>
        </li>
        <li {% if section == "images" %}class="selected"{% endif %}>
            <a href="{% url "images:list" %}">Images</a>
        </li>
        <li {% if section == "websites" %}class="selected"{% endif %}>
            <a href="{% url "websites:list" %}">Websites</a>
        </li>
        <li>
            <a href="{% url "logout" %}">Logout</a>
        </li>
        {% else %}
            <a href="{% url "login" %}">Log-in</a>
        {% endif %}
    </ul>

    <div id="content">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                            <a href="#" class="close">✖</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% block content %}
        {% endblock %}
        <br clear="all" />
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src=" https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
	<script type="text/javascript" src="{% static 'js/main_js.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.showYtVideo.js' %}"></script>
	 <script>var banner_default = "{% static 'css/global_images/mediashelf_banner1.jpg' %}";</script>
<script>
 $(document).ready(function ($) {
            $('.demo').on('click', function () {
                $.showYtVideo({
                    videoId: 'SayaFaahEuc'
                });
            });
        });
</script>
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function(){
            {% block domready %}
 setInterval(function () {
        moveRight();
    }, 8000);

	var slideCount = $('#slider ul li').length;
	var slideWidth = $('#slider ul li').width();
	var slideHeight = $('#slider ul li').height();
	var sliderUlWidth = slideCount * slideWidth;

	$('#slider').css({ width: slideWidth, height: slideHeight });

	$('#slider ul').css({ width: sliderUlWidth, marginLeft: - slideWidth });

    $('#slider ul li:last-child').prependTo('#slider ul');

    function moveLeft() {
        $('#slider ul').animate({
            left: + slideWidth
        }, 200, function () {
            $('#slider ul li:last-child').prependTo('#slider ul');
            $('#slider ul').css('left', '');
        });
    };

    function moveRight() {
        $('#slider ul').animate({
            left: - slideWidth
        }, 500, function () {
            $('#slider ul li:first-child').appendTo('#slider ul');
            $('#slider ul').css('left', '');
        });
    };

    $('a.control_prev').click(function () {
        moveLeft();
    });

    $('a.control_next').click(function () {
        moveRight();
    });
            {% endblock %}
            });
    </script>
<div class="modal-backdrop"></div>
</body>
</html>

account/templates/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

account/templates/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a
href="{% url "login" %}">log in</a>.</p>
{% endblock %}