bookmarks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'', include('mainpage.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
	url(r'^websites/', include('websites.urls', namespace='websites')),
    url(r'^api/v1/', include('core_apis.urls', namespace='api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^image-edit/(?P<image_id>\d+)/$', views.image_edit, name='image_edit'),
    url(r'^image-delete/(?P<image_id>\d+)/$', views.image_delete, name='image_delete'),
    url(r'^search/$', views.search, name='image-search'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse


# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            related_name='images_created')
    title = models.CharField(max_length=220)
    slug = models.SlugField(max_length=220,
                            blank=True)
    url = models.TextField(max_length=400)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True,
                            db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    version = models.CharField(max_length=40)

    class Meta:
    	ordering = ["-created"]
    def __str__(self):
         return self.title

    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)
        else:
           super(Image, self).save(*args, **kwargs) 

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
import urllib

class AppURLopener(urllib.request.FancyURLopener):
	version = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"

opener = AppURLopener()
class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg','png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not ' \
                                        'match valid image extensions.')
        return url
    
    def save(self, force_insert=False,
                    force_update=False,
                    commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                image_url.rsplit('.', 1)[1].lower())
        # download image from the given URL
        response = opener.open(image_url)
        image.image.save(image_name,
                        ContentFile(response.read()),
                        save=False)
        if commit:
            image.save()
        return image
    
class ImageEditForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'description')
        
class ImageDeleteForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = []      
       

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from common.search import *
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
import json
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.utils.text import slugify
from actions.utils import create_action
from images.serializers import ImageSerializer
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
import random
import hashlib
# Create your views here.
@login_required
def image_create(request):
    version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)

            # assign current user to the item
            new_item.user = request.user
            new_item.version = version
            new_item.save()
            create_action(request.user, 'Saved: ' + new_item.title, 'Image', new_item)
            messages.success(request, 'Image added successfully')

            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)

    return render(request,
                'images/image/create.html',
                {'section': 'images',
                'form': form})

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request,
                'images/image/detail.html',
                {'section': 'images',
                'image': image})

@login_required
def image_list(request):
    user = request.user
    images = Image.objects.filter(user= user)
    if request.is_ajax():
        return render(request,
                        'images/image/responsive-image-list.html',
                        {'section': 'images', 'images': images})
    return render(request,
                    'images/image/list.html',
                    {'section': 'images', 'images': images})

@ajax_required
@login_required
def image_edit(request, image_id):
	data = json.loads(request.body.decode("utf-8"))
	user = request.user
	title = data[0]['title']
	description = data[0]['description']
	version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
	image = Image.objects.get(pk=image_id)
	image.title=title
	image.slug=slugify(title)
	image.description=description
	image.version=version
	image.save()
	return JsonResponse({'status':'success'})


@ajax_required
@login_required
def image_delete(request, image_id):
    image = Image.objects.get(pk=image_id)
    create_action(request.user, 'Deleted: ' + image.title, 'Image',  image)
    image.delete()
    return JsonResponse({'status': 'Deleted successfuly!'})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})


@login_required
def search(request):
	query_string = ''
	images = None
	if ('q' in request.GET) and request.GET['q'].strip():
		query_string = request.GET['q']
		entry_query = get_query(query_string, ['title', 'description' ])
		images = Image.objects.filter(entry_query)
	return render(request,'images/image/list.html',{'section': 'images', 'images': images})

class ImageList(generics.ListCreateAPIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = ImageSerializer
    def get_queryset(self):
        user = self.request.user
        return Image.objects.filter(user=user)

class ImageDetail(generics.RetrieveUpdateDestroyAPIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = ImageSerializer
    def get_queryset(self):
        user = self.request.user
        return Image.objects.filter(user=user)

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Save an image{% endblock %}

{% block content %}
<style>
#image-to-save img{
margin-top:16px !important;
}
</style>
    <h1>Save an Image</h1>
<div id="image-to-save">    
<img src="{{ request.GET.url }}" class="image-preview">
</div>   
     <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
       <input type="submit" value="Save it!">
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>
        {% load thumbnail %}
            {% thumbnail image.image "400x600" as im %}
            <a href="{{ image.image.url }}">
            <img src="{{ im.url }}" class="image-detail">
            </a>
        {% endthumbnail %}
            <div class="image-info">
            
            {{ image.description|linebreaks }}
        </div>
   
    </div>

{% endblock %}

images/templates/images/image/image_delete.html
{% extends "base.html" %}




{% block content %}

    <h1>{% block title %}Delete your Image{% endblock %}</h1>

    <img src="{{ image.url }}" class="image-detail">

    <form action="." method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Delete Image"></p>
    </form>
 
{% endblock %}

images/templates/images/image/image_edit.html
{% extends "base.html" %}




{% block content %}

    <h1>{% block title %}Edit your Image{% endblock %}</h1>

    <img src="{{ image.url }}" class="image-detail">

    <form action="" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
 
{% endblock %}
 

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images Saved{% endblock %}

{% block content %}
<section class="title-bar">
    <h1>Images Saved</h1>
    <form id="searchform" action="{% url 'images:image-search' %}" method="get" accept-charset="utf-8">
<button class="searchbutton" type="submit">
  <i class="fa fa-search"></i>
</button>
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
</form>
<br clear="all" />
</section>
	<div class="image-table-responsive">
    	<div id="image-list">

    		{% include 'images/image/responsive-image-list.html' %}
		</div>
    </div>
{% endblock %}

        <script>

            function pageShown(evt){
                if (evt.persisted) {
                    alert("pageshow event handler called.  The page was just restored from the Page Cache (eg. From the Back button.");
                } else {
                    alert("pageshow event handler called for the initial load.  This is the same as the load event.");
                }
            }

            function pageHidden(evt){
                if (evt.persisted) {
                    alert("pagehide event handler called.  The page was suspended and placed into the Page Cache.");
                } else {
                    alert("pagehide event handler called for page destruction.  This is the same as the unload event.");
                }
            }

            window.addEventListener("pageshow", pageShown, false);
            window.addEventListener("pagehide", pageHidden, false);

        </script>

images/templates/images/image/list_ajax.html
<div class="image-table-responsive">
    {% include 'images/image/responsive-image-list.html' %}
</div>

images/templates/images/image/responsive-image-list.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop="top" as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}">                        
                </a>
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
			<p class="description">{{image.description}}</p>
        </div>
		<ul class="buttons">
        <li class="deleteButton" id ="{{image.id}}">
        <i class="fa fa-trash"></i>
		<div class="id-text" id="delete"  style="text-align: center">Delete</div>
        </li>
        <li class="imageEditButton" id ="{{image.id}}">
        <i class="fa fa-pencil-square-o"></i>
		    <div class="id-text" id="edit"  style="text-align: center">Edit</div>
        </li>
	        <li class="downloadButton" id ="download">
        <a href="{{image.image.url}}" download><i class="fa fa-download"></i></a>
        <div class="id-text" id="download-image"  style="text-align: center">Download</div>
        </li>
		</ul>
    </div>
{% endfor %}


        <div class="delete-form-mini-container">

	<header class="popupHeader">
		<span class="header_title">Are you sure?</span>
		<span class="modal_close"><i class="fa fa-window-close"></i></span>
	</header>
            <a class="idHolder" id=""></a>

            <form class="delete-form-mini" method="post" action="">


                <div class="form-row form-last-row">
                    <button class="cancel" type="submit">Cancel</button>
                </div>

                <div class="form-row form-last-row">
                    <button class="delete-image" type="submit">Delete</button>
                </div>

            </form>
        </div>


<div class="image-edit-form-mini-container">
	<header class="popupHeader">
		<span class="header_title">Edit Image</span>
		<span class="edit-modal-close"><i class="fa fa-window-close"></i></span>
	</header>
           			<a class="idHolder" id=""></a> 
            <form class="form-mini" method="post" action="">
				
				<div class="video-image"><img src=""></div>
                <div class="form-row">
                    <input id="title" type="text" name="title" value="" >
                </div>


                <div class="form-row">
<textarea rows="6" cols="25"></textarea>

                </div>


                <div class="form-row form-last-row">
					
                    <button id="editImageSubmit" type="submit">Submit</button>
                </div>

            </form>
        </div>