bookmarks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'', include('mainpage.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
	url(r'^websites/', include('websites.urls', namespace='websites')),
    url(r'^api/v1/', include('core_apis.urls', namespace='api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^image-edit/(?P<image_id>\d+)/$', views.image_edit, name='image_edit'),
    url(r'^image-delete/(?P<image_id>\d+)/$', views.image_delete, name='image_delete'),
    url(r'^search/$', views.search, name='image-search'),
]

websites/urls.py
from django.conf.urls import url,patterns
from . import views



urlpatterns = [
	url(r'^website/$', views.websiteSave, name='websiteSave'),
	url(r'^mobile-save/$', views.mobile_save, name='mobile-save'),
	url(r'^$', views.websiteList, name='list'),
    url(r'^website-delete/(?P<website_id>\d+)/$', views.website_delete, name='website_delete'),
    url(r'^website-edit/(?P<website_id>\d+)/$', views.website_edit, name='website_edit'),
    url(r'^search/$', views.search, name='website-search'),
]

websites/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Website(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            related_name='website_saved')
	site_name = models.CharField(max_length=220)
	url = models.URLField(max_length=400)
	category = models.CharField(max_length=220)
	favicon_url = models.URLField(max_length=220)
	favicon = models.ImageField(upload_to='website_favicons/%Y/%m/%d', default='website_favicons/Internet-icon.png', blank=True)
	created = models.DateTimeField(auto_now_add=True,
                            db_index=True)
	version = models.CharField(max_length=40)
	class Meta:
    		ordering = ["-created"]
	def __str__(self):
		return self.site_name

websites/views.py
from django.shortcuts import render
import json
from django.contrib.auth.decorators import login_required
from common.decorators import ajax_required
from common.search import *
from django.http import JsonResponse
from actions.utils import create_action
from .models import Website
from django.core.files.base import ContentFile
import urllib.request
from urllib.parse import urlparse
from django.utils import timezone
from websites.serializers import WebsiteSerializer
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from django.views.decorators.csrf import csrf_exempt
from pyquery import PyQuery as pq
from lxml import etree
import random
import hashlib

# Create your views here.

@csrf_exempt
def websiteSave(request):
	if str(request.user) == 'AnonymousUser':
		response_data = {"status":"login"}
		return JsonResponse(response_data)
	else:
		data = (json.loads(request.read().decode('utf-8')))
		user = request.user
		site_name = data[0]['site_name']
		if site_name[0:4] == 'www.':
			site_name = site_name[4:]
		url = data[0]['url']
		category = data[0]['category']
		favicon_url=data[0]['favicon_url']
		version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
		website_instance = Website.objects.create(user=user, site_name=site_name, url=url, category=category, favicon_url=favicon_url, version=version)
		class AppURLopener(urllib.request.FancyURLopener):
			version = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
		opener = AppURLopener()
		name = str(timezone.now().microsecond) + urlparse(favicon_url).path.split('/')[-1]
		if favicon_url != '':
			response = opener.open(favicon_url)
			favicon = ContentFile(response.read())
			website_instance.favicon.save(name, favicon)
		create_action(request.user, 'Saved: ' + site_name, 'Website', website_instance)

		return JsonResponse({'status':'Saved successfully!'})


@csrf_exempt
@login_required
def mobile_save(request):
	if str(request.user) == 'AnonymousUser':
		return JsonResponse({"status":"login"})
	else:
		#print('begin')
		data = (json.loads(request.read().decode('utf-8')))
		user = request.user
		#print(user)
		this_url = data[0]['url']
		category=data[0]['category']
		site_url = urlparse(this_url)
		site_name = site_url.netloc
		if site_name[0:4] == 'www.':
			site_name = site_name[4:]
		d = pq(url=this_url)
		favicon_list = d('link')
		#print('ok1')
		def ValidateUrl(test_url):
			global valid_url
			o = urlparse(test_url)
			if bool(o.scheme) == True and o.scheme[0:2] == 'ht':
				valid_url=test_url
			elif test_url[0:2] != 'ht':
				if str(test_url)[0:2] == '//':
					valid_url = site_url.scheme + ':' + test_url
				elif str(test_url)[0:1] == '/':
					valid_url = site_url.scheme + '://' + site_url.netloc + test_url
				else:
					pass

		for each in favicon_list:
			if d(each).attr('rel') == 'icon' or d(each).attr('rel')== "shortcut icon":
				favicon_url = (d(each).attr('href'))
				ValidateUrl(favicon_url)
			else:
				valid_url = ''
		version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
		website_instance = Website.objects.create(user=user, site_name=site_name, url=this_url, category=category, favicon_url=favicon_url, version=version)	
		#print('ok2')
		class AppURLopener(urllib.request.FancyURLopener):
			version = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
		opener = AppURLopener()
		name = str(timezone.now().microsecond) + urlparse(favicon_url).path.split('/')[-1]
		if valid_url != '':
			response = opener.open(valid_url)
			favicon = ContentFile(response.read())
			website_instance.favicon.save(name, favicon)
		#print('4')
		create_action(request.user, 'Saved: ' + site_name, 'Website', website_instance)

		return JsonResponse({'status':'Saved successfully!'})


@login_required
def websiteList(request):
    user = request.user
    websites = Website.objects.filter(user= user)
    categories = Website.objects.filter(user=user).values_list('category', flat=True).distinct().exclude(category__isnull=True).exclude(category__exact=' ').order_by('category')
    if request.is_ajax():
        return render(request,
                        'websites/responsive_website_list.html',
                        {'section': 'websites', 'websites': websites})
    return render(request,
                    'websites/website_list.html',
                    {'section': 'websites', 'websites': websites, 'categories': categories})


@ajax_required
@login_required
def website_delete(request, website_id):
	website = Website.objects.get(pk=website_id)
	create_action(request.user, 'Deleted: ' + website.url, 'website', website)
	website.delete()
	return JsonResponse({'status':'Deleted successfully!'})


@ajax_required
@login_required
def website_edit(request, website_id):
	data = json.loads(request.body.decode("utf-8"))
	user = request.user
	site_name = data[0]['site_name']
	category = data[0]['category']
	version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
	website = Website.objects.get(pk=website_id)
	website.site_name=site_name
	website.category=category
	website.version=version
	website.save()
	return JsonResponse({'status':'Success!'})


@login_required
def search(request):
	user=request.user
	query_string = ''
	websites = None
	categories = None
	if ('q' in request.GET) and request.GET['q'].strip():
		query_string = request.GET['q']
		title_entry_query = get_query(query_string, ['site_name', ])
		websites = Website.objects.filter(user=user).filter(title_entry_query)
		categories = Website.objects.filter(user=user).filter(title_entry_query).values_list('category', flat=True).distinct().exclude(category__isnull=True).exclude(category__exact=' ').order_by('category')
	return render(request,'websites/website_list.html',{'section': 'websites', 'websites': websites, 'categories': categories})


class WebsiteList(generics.ListCreateAPIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = WebsiteSerializer
    def get_queryset(self):
        user = self.request.user
        return Website.objects.filter(user=user)

class WebsiteDetail(generics.RetrieveUpdateDestroyAPIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = WebsiteSerializer
    def get_queryset(self):
        user = self.request.user
        return Website.objects.filter(user=user)

websites/templates/websites/responsive_website_list.html
{% load thumbnail %}
{% load social_share %}
{% for website in websites %}

    <div class="image" id="{{website.id}}">
<ul class="friend-div" id= "{{website.id}}">
<li class="fb-post">{% post_to_facebook website.url "Post to Facebook" %}</li>
<li class="twitter-post">{% post_to_twitter "Website: {{website.site_name}}. Check it out!" website.url "Post to Twitter" %}</l>
<li class="email-post">{% send_email website.site_name "Website: {{website.site_name}}. Check it out!" website.url "Share via email" %}</li>
</ul>
    <section id="favicon-holder">
		<a href="{{ website.url }}">
            {% thumbnail  website.favicon "30x30" crop="center" format="PNG" as im %}
                    <img id="site-favicon" src="{{im.url}}">
            {% endthumbnail %}
		</a>
    </section>
        <div class="info">
            <a href="{{ website.url }}" class="title">
                {{ website.site_name }}
            </a>
			<a class="category">
                {{ website.category }}
            </a>
        </div>
<ul class="buttons">
        <li class="deleteButton" id ="{{website.id}}">
        <i class="fa fa-trash"></i>
		<div class="id-text" id="website-delete"  style="text-align: center">Delete</div>
        </li>
        <li class="editButton" id ="{{website.id}}">
        <i class="fa fa-pencil-square-o"></i>
		    <div class="id-text" id="website-edit"  style="text-align: center">Edit</div>
        </li>
        <li class="friendButton" id ="{{website.id}}">
        <i class="fa my-fa-friends"></i>
		    <div class="id-text" id="website-share"  style="text-align: center">Share</div>
        </li>
		</ul>
	</div>
{% endfor %}

        <div class="delete-form-mini-container">

	<header class="popupHeader">
		<span class="header_title">Are you sure?</span>
		<span class="modal_close"><i class="fa fa-window-close"></i></span>
	</header>
            <a class="idHolder" id=""></a>

            <form class="delete-form-mini" method="post" action="">


                <div class="form-row form-last-row">
                    <button class="cancel" type="submit">Cancel</button>
                </div>

                <div class="form-row form-last-row">
                    <button class="delete-website" type="submit">Delete</button>
                </div>

            </form>
        </div>
<div class="edit-form-mini-container">
	<header class="popupHeader">
		<span class="header_title">Edit Website</span>
		<span class="edit-modal-close"><i class="fa fa-window-close"></i></span>
	</header>
           			<a class="idHolder" id=""></a>
            <form class="form-mini" method="post" action="">

				<div class="video-image"><img src=""></div>
                <div class="form-row">
                    <input id="title" type="text" name="title" value="" >
                </div>


                <div class="form-row">
                    <label>
                        <select  name="dropdown">
                            <option>Arts</option>
                            <option>Business</option>
                            <option>Economics</option>
                            <option>Education</option>
                            <option>Entertainment</option>
                            <option>Fashion</option>
                            <option>Games</option>
                            <option>Health</option>
                            <option>Home</option>
                            <option>Kids</option>
                            <option>Men</option>
                            <option>News</option>
                            <option>Politics</option>
                            <option>Reference</option>
                            <option>Regional</option>
                            <option>Science</option>
                            <option>Shopping</option>
                            <option>Society</option>
                            <option>Sports</option>
                            <option>Technology</option>
                            <option>Travel</option>
                            <option>Women</option>
                            <option>Miscellaneous</option>
                        </select>
                    </label>
                </div>


                <div class="form-row form-last-row">

                    <button id="editWebsiteSubmit" type="submit">Submit</button>
                </div>

            </form>
        </div>


<div class="friend-form-mini-container">

	<header class="popupHeader">
		<span class="header_title">Share This Now!</span>
		<span class="friend-modal-close"><i class="fa fa-window-close" aria-hidden="true"></i></span>
	</header>
           <a class="idHolder" id=""></a>

            <form class="friend-form-mini" method="post" action="#">

				<div class="item-image"><img src=""></div>


               <div class="form-row form-last-row">

                    <a class="friend-button" id="fb" href=""><i class="fa fa-my-zuck"></i><span>Post to Facebook</span></a>
                </div>

               <div class="form-row form-last-row">
                    <a class="friend-button" id="twitter" href =""><i class="fa fa-my-bird" aria-hidden="true"></i><span>Post to Twitter</span></a>
                </div>
               <div class="form-row form-last-row">
                    <a class="friend-button" id="email" href=""><i class="fa fa-envelope" aria-hidden="true"></i><span>Share via Email</span></a>
                </div>
               <div class="form-row form-last-row">
                    <a class="friend-button"><div class="media-shelf-icon"></div><span>Share via MediaShelf</span></a>
                </div>
        </form>
    </div>

websites/templates/websites/website_list.html
{% extends "base.html" %}

{% block title %}Websites Saved{% endblock %}

{% block content %}
<section class="title-bar" id="website-title-bar">
    <h1>Websites Saved</h1>
    <form id="searchform" action="{% url 'websites:website-search' %}" method="get" accept-charset="utf-8">
<button class="searchbutton" type="submit">
  <i class="fa fa-search"></i>
</button>
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
</form>
<div id="mobile-search-icon">
  <i class="fa fa-search fa-2x" aria-hidden="true"></i>
</div>
<div class="search-dropdown">
  <form id="dropdown-searchform" action="{% url 'websites:website-search' %}" method="get" accept-charset="utf-8">
<button class="searchbutton" type="submit">
<i class="fa fa-search"></i>
</button>
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
</form>
</div>
<br clear="all" />
</section>
<div id="item-content">
    <div id="website-list">
		<div class="website-table-responsive">
    		{% include 'websites/responsive_website_list.html' %}
		</div>
    </div>
</div>
    <div id="right-sidebar">


      <h2>Filter by Category</h2>
      <fieldset>
        <div class="item">
         <input type = "radio"
        name="action"
           id = "chkAll"
           value = "All" />
         <label for = "all">All</label>
       </div>
{% for category in categories %}
 <div class="item">
  <input type = "radio"
	name="action"
    id = "chk{{category}}"
    value = "{{category}}" />
  <label for = "{{category}}">{{category}}</label>
</div>
{% endfor %}
</fieldset>
 <br clear="all" />
<button type = "button"
  id = "filter_button">
 Filter
</button>
    </div>

  <div class="filter-dropdown">
      <h2>Filter by Category</h2>
      <fieldset id="fieldset">
        <div class="item">
         <input type = "radio"
        name="action"
           id = "chkAll"
           value = "All" />
         <label for = "all">All</label>
       </div>
    {% for category in categories %}
    <div class="item">
    <input type = "radio"
    name="action"
    id = "chk{{category}}"
    value = "{{category}}" />
    <label for = "{{category}}">{{category}}</label>
    </div>
    {% endfor %}
    </fieldset>
    <br clear="all" />
    <button type = "button"
    id = "filter_button">
    Filter
    </button>
    </div>
{% endblock %}