articles/urls.py
from django.conf.urls import url,patterns
from . import views
from wkhtmltopdf.views import PDFTemplateView


urlpatterns = [
	url(r'^article/$', views.article_save, name='article'),
	url(r'^mobile-save/$', views.mobile_save, name='mobile-save'),
	url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.article_detail, name='detail'),
	url(r'^$', views.article_list, name='list'),
    url(r'^article-delete/(?P<article_id>\d+)/$', views.article_delete, name='article_delete'),
    url(r'^article-edit/(?P<article_id>\d+)/$', views.article_edit, name='article_edit'),
    url(r'^search/$', views.search, name='article-search'),
	url(r'^pdf/(?P<article_id>\d+)/$', views.generate_pdf, name='pdf'),
]

bookmarks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'', include('mainpage.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
	url(r'^websites/', include('websites.urls', namespace='websites')),
    url(r'^api/v1/', include('core_apis.urls', namespace='api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^image-edit/(?P<image_id>\d+)/$', views.image_edit, name='image_edit'),
    url(r'^image-delete/(?P<image_id>\d+)/$', views.image_delete, name='image_delete'),
    url(r'^search/$', views.search, name='image-search'),
]

articles/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import SmartResize, ResizeToFit
# from django.core.files import File
# import urllib
# from io import BytesIO
# from urllib.request import urlopen
# from urllib.parse import urlparse
# from django.core.files.temp import NamedTemporaryFile
# import os
# from urllib import request
# from django.core.files.base import ContentFile
# Create your models here.


class Article(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            related_name='articles_saved')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200,
                            blank=True)
	category = models.CharField(max_length=200)
	url = models.URLField(max_length=500)
	saved_on = models.DateTimeField(auto_now_add=True)
	version = models.CharField(max_length=40)
	class Meta:
    		ordering = ["-saved_on"]

	def __str__(self):
 		return self.title

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
			super(Article, self).save(*args, **kwargs)
		else:
			super(Article, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('articles:detail', args=[self.id, self.slug])


class Image(models.Model):
	article = models.ForeignKey(
	    Article, on_delete=models.CASCADE, null=True, related_name='image')
	image_url = models.TextField(max_length=500)
	image = ProcessedImageField(upload_to='article_images/%Y/%m/%d', blank=True,
                                           processors=[ResizeToFit(500)],
                                           format='JPEG',
                                           options={'quality': 70})

	def __str__(self):
		return self.image_url
	def get_absolute_url(self):
		return reverse('articles:detail', args=[self.article.id, self.article.slug])

class Node(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, related_name='node')
	#user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            #related_name='user', default=1)
	image = models.ForeignKey(Image, on_delete=models.CASCADE, null=True, blank=True, related_name='node')
	node = models.IntegerField(default=0)
	html_element = models.CharField(max_length=200)
	content = models.TextField(default='blank', max_length=800)

	class Meta:
		ordering = ('node',)
	def __str__(self):
		return self.content

articles/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageSaveForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image_url',)

    def save(self, force_insert=False,
                    force_update=False,
                    commit=True):
        image = super(ImageSaveForm, self).save(commit=False)
        image_url = self.cleaned_data['image_url']
        image_name = '{}.{}'.format(
                                image_url.rsplit('.', 1)[1].lower())
        # download image from the given URL
        response = request.urlopen(image_url)
        image.image.save(image_name,
                        ContentFile(response.read()),
                        save=True)
        image.save()
        

articles/views.py
from django.contrib.auth.decorators import login_required
from common.decorators import ajax_required
from common.search import *
from django.shortcuts import render, redirect
from django.utils import timezone
import json
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponse
from .models import Article, Node, Image
from urllib.request import urlopen
from urllib.parse import urlparse
from urllib import request
from django.core.files.base import ContentFile
import urllib.request
from django.utils.text import slugify
import pdfkit
from django.template.loader import get_template
from django.template import Context
import os
from actions.utils import create_action
from django.views.decorators.csrf import csrf_exempt
from articles.serializers import ArticleSerializer
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from pyquery import PyQuery as pq
from lxml import etree
from PIL import Image as images
from io import BytesIO
import requests
import random
import hashlib
# Create your views here.

@csrf_exempt
def article_save(request):
	if str(request.user) == 'AnonymousUser':
		response_data = {"status":"login"}
		return JsonResponse(response_data)
	else:
		beginning=timezone.now()
		data = (json.loads(request.read().decode('utf-8')))
		user = request.user
		title = data[0]['title']
		category = data[0]['category']
		url = data[0]['url']
		version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
		article_instance= Article.objects.create(user=user, title=title, category=category, url=url, version=version)
		class AppURLopener(urllib.request.FancyURLopener):
			version = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
		opener = AppURLopener()
		data=data[1:]
		instances = []
		for item in data:
			if item['html_element']=='img':
				node=item['node']
				image_url = item['content']
				html_element=item['html_element']
				name = str(timezone.now().microsecond) + urlparse(image_url).path.split('/')[-1]
				name = name[0:50]
				response = opener.open(image_url)
				image_content = ContentFile(response.read())
				image_instance = Image(article=article_instance, image_url=image_url)
				image_instance.image.save(name, image_content)
				instances.append(Node(
						article=article_instance,
						#user=user,
						image=image_instance,
						node=node,
						html_element=html_element,
						content=image_url,
				))
				#node_instance = Node.objects.create(article=article_instance, image=image_instance, node=node, html_element=html_element, content=image_url)
			else:
				#Node.objects.create(article=article_instance, node=item['node'], content=item['content'], html_element=item['html_element'])
				instances.append(Node(
					article=article_instance,
					node=item['node'],
					html_element=item['html_element'],
					content=item['content'],
						))
		Node.objects.bulk_create(instances)
		create_action(request.user, 'Saved: ' + title, 'Article', article_instance)
		return JsonResponse({'status':'Saved successfully!'})

@csrf_exempt
@login_required
def mobile_save(request):
	if str(request.user) == 'AnonymousUser':
		return JsonResponse({"status":"login"})
	else:
		data = (json.loads(request.read().decode('utf-8')))
		user = request.user
		#print(user)
		this_url = data[0]['url']
		category=data[0]['category']
		d = pq(url=this_url)
		get_article= d('p,img')
		#print(get_article)
		title = d('title').text()
		version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
		#print('ok1')
		article_instance= Article.objects.create(user=user, title=title, category=category, url=this_url, version=version)	
		#print('ok2')
		class AppURLopener(urllib.request.FancyURLopener):
			version = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
		opener = AppURLopener()
		instances = []
		def ValidateUrl(test_url):
			global valid_url
			site_url = urlparse(this_url)
			o = urlparse(test_url)
			if bool(o.scheme) == True and o.scheme[0:2] == 'ht':
				valid_url=test_url
			elif test_url[0:2] != 'ht':
				if str(test_url)[0:2] == '//':
					valid_url = site_url.scheme + ':' + test_url
				elif str(test_url)[0:1] == '/':
					valid_url = site_url.scheme + '://' + site_url.netloc + test_url
				else:
					pass
		#print('ok3')
		for i in range(get_article.length):
			if d(get_article[i]).is_(':hidden'):
				pass
			if d(get_article[i]).is_('p'):
				if d(get_article[i]).is_(':contains("Advertisement")') or d(get_article[i]).is_(':contains("ADVERTISEMENT")'):
					pass
				else:
					instances.append(Node(
						article=article_instance,
						node=i,
						html_element='p',
						content=d(get_article[i]).text(),
							))	
					#print('p')
			elif d(get_article[i]).is_('img'):
				ValidateUrl(d(get_article[i]).attr('src'))
				#print(valid_url)
				if d(get_article[i]).width() and (int(d(get_article[i]).width()) > 210):
					name = str(timezone.now().microsecond) + urlparse(valid_url).path.split('/')[-1]
					response = opener.open(valid_url)
					image_content = ContentFile(response.read())
					image_instance = Image(article=article_instance, image_url=str(valid_url))
					image_instance.image.save(name, image_content)
					instances.append(Node(
							article=article_instance,
							image=image_instance,
							node=i,
							html_element='img',
							content=valid_url,
					))
					#print('img')
				elif d(get_article[i]).width() == None:
					response = requests.get(valid_url)
					#print('ok4')
					img = images.open(BytesIO(response.content))
					#print('img opened')
					width, height = img.size
					#print(width)
					if width > 210:
						name = str(timezone.now().microsecond) + urlparse(valid_url).path.split('/')[-1]
						#print(name)
						#print(valid_url)
						response = opener.open(valid_url)
						#print(response)
						image_content = ContentFile(response.read())
						#print(image_content)
						image_instance = Image(article=article_instance, image_url=valid_url)
						#print('image instance created')
						image_instance.image.save(name, image_content)
						#print('image just saved')
						instances.append(Node(
								article=article_instance,
								image=image_instance,
								node=i,
								html_element='img',
								content=valid_url,
						))
						#print('img saved')
		Node.objects.bulk_create(instances)
		create_action(request.user, 'Saved: ' + title, 'Article', article_instance)
		return JsonResponse({'status':'Saved successfully!'})


@login_required
def article_detail(request, id, slug):
	article = get_object_or_404(Article, id=id, slug=slug)
	nodes = Node.objects.filter(article =article )
	return render(request, 'articles/article_view.html',
{'section': 'articles','article': article, 'nodes': nodes})

@login_required
def article_list(request):
    user = request.user
    articles = Article.objects.filter(user= user)
    categories = Article.objects.filter(user=user).values_list('category', flat=True).distinct().exclude(category__isnull=True).exclude(category__exact=' ').order_by('category')
    if request.is_ajax():
        return render(request,
                        'articles/responsive_article_list.html',
                        {'section': 'articles', 'articles': articles})
    return render(request,
                    'articles/article_list.html',
                    {'section': 'articles', 'articles': articles, 'categories': categories})
@ajax_required
@login_required
def article_delete(request, article_id):
	article = Article.objects.get(pk=article_id)
	create_action(request.user, 'Deleted: ' + article.title, 'Article', article)
	article.delete()
	return JsonResponse({'status':'Deleted successfully!'})


@ajax_required
@login_required
def article_edit(request, article_id):
	data = json.loads(request.body.decode("utf-8"))
	user = request.user
	title = data[0]['title']
	category = data[0]['category']
	version = hashlib.sha1((str(random.random())).encode('utf8')).hexdigest()[:5]
	article = Article.objects.get(pk=article_id)
	article.title=title
	article.slug=slugify(title)
	article.category=category
	article.version=version
	article.save()
	return JsonResponse({'status':'Success!'})

@login_required
def generate_pdf(request, article_id):
	user = request.user
	template = get_template("articles/article_view_pdf.html")
	article = Article.objects.get(pk=article_id)
	nodes = Node.objects.filter(article = article)
	context = Context({'article': article, 'nodes': nodes})  # data is the context data that is sent to the html file to render the output.
	html = template.render(context)  # Renders the template with the context data.)
	options = {
        'margin-top': '0.50in',
        'margin-right': '.55in',
        'margin-bottom': '0.55in',
        'margin-left': '.55in',
}
	filename = article.slug
	print(filename)
	#filename=filename.translate({ord(i):None for i in '|'})
	pdfkit.from_string(html, 'out.pdf', options=options)
	pdf = open("out.pdf", "rb")
	response = HttpResponse(pdf.read(), content_type='application/pdf')  # Generates the response as pdf response.
	response['Content-Disposition'] = 'attachment; filename = %s.pdf' % filename
	pdf.close()
	os.remove("out.pdf")  # remove the locally created pdf file.
	return response  # returns the response.

@login_required
def search(request):
	user=request.user
	query_string = ''
	title_entries = None
	found_entries = None
	articles= None
	categories=None
	if ('q' in request.GET) and request.GET['q'].strip():
		query_string = request.GET['q']
		entry_query = get_query(query_string, ['title','node__content' ])
		#entry_query = get_query(query_string, ['content', ])

articles/templates/articles/article_list.html
{% extends "base.html" %}

{% block title %}Articles Saved{% endblock %}

{% block content %}
<section class="title-bar">
    <h1>Articles Saved</h1>
    <form id="searchform" action="{% url 'articles:article-search' %}" method="get" accept-charset="utf-8">
<button class="searchbutton" type="submit">
  <i class="fa fa-search"></i>
</button>
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
</form>
<div id="mobile-search-icon">
  <i class="fa fa-search fa-2x" aria-hidden="true"></i>
</div>
<div class="search-dropdown">
  <form id="dropdown-searchform" action="{% url 'articles:article-search' %}" method="get" accept-charset="utf-8">
<button class="searchbutton" type="submit">
<i class="fa fa-search"></i>
</button>
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
</form>
</div>
<br clear="all" />
</section>
<div id="item-content">
    <div id="article-list">
		<div class="article-table-responsive">
    		{% include 'articles/responsive_article_list.html' %}
		</div>
    </div>
</div>
    <div id="right-sidebar">


      <h2>Filter by Category</h2>
      <fieldset id="fieldset">
        <div class="item">
         <input type = "radio"
       	name="action"
           id = "chkAll"
           value = "All" />
         <label for = "all">All</label>
       </div>
{% for category in categories %}
 <div class="item">
  <input type = "radio"
	name="action"
    id = "chk{{category}}"
    value = "{{category}}" />
  <label for = "{{category}}">{{category}}</label>
</div>
{% endfor %}
</fieldset>
 <br clear="all" />
<button type = "button"
  id = "filter_button">
 Filter
</button>
    </div>

<div class="filter-dropdown">
  <h2>Filter by Category</h2>
  <fieldset id="fieldset">
    <div class="item">
     <input type = "radio"
    name="action"
       id = "chkAll"
       value = "All" />
     <label for = "all">All</label>
   </div>
{% for category in categories %}
<div class="item">
<input type = "radio"
name="action"
id = "chk{{category}}"
value = "{{category}}" />
<label for = "{{category}}">{{category}}</label>
</div>
{% endfor %}
</fieldset>
<br clear="all" />
<button type = "button"
id = "filter_button">
Filter
</button>
</div>
{% endblock %}

articles/templates/articles/article_list_ajax.html
<div class="article-table-responsive">
    {% include 'articles/responsive_article_list.html' %}
</div>

articles/templates/articles/article_view.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ article.title }}{% endblock %}

{% block content %}
<h1>{{ article.title }}</h1>
<div id="main-content">

<div id="article-view">
<section id="top-section">
<div id="original-url"><a href="{{ article.url }}">View Original</a></div>
<div id="pdf">
    <div id="pdf-text">Download Pdf</div>
<div id="download-pdf" ><a class="icon" href="{% url 'articles:pdf' article.id %}"><i class="fa fa-download" aria-hidden="true"></i></a></div>
</div>
</section>
{% for each in nodes %}

{% if each.html_element == "img"%}
<div class="image-node">
{% thumbnail  each.image.image "760x540" crop="top" as im %}
    <img src="{{ im.url}}">

{% endthumbnail %}
</div>
{% else %}
<div class="text-node">
    <p>{{each.content}}</p>
</div>
{% endif %}
{% endfor %}
</div>
</div>

{% endblock %}

articles/templates/articles/article_view_pdf.html
{% load thumbnail %}

{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static "css/icons/media_shelf.png" %}">
    <link href= "{% static "css/base.css" rel="stylesheet" %}>
	<link href= "{% static "css/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet"%}>
	<meta charset="utf-8" />
</head>
<body>
    <div id="header">
        <span class="logo"></span>
    </div>
<div id="content">
{% block content %}
<h1>{{ article.title }}</h1>
<div>Source:{{article.url}}</div>
<div id="article-main-content-pdf">

<div id="article-view-pdf">

{% for node in nodes %}



{% if node.html_element == "img"%}
<div class="image-node">
{% thumbnail  node.image.image "630x450" crop="top" as im %}
    <img src="{{ im.url}}"> 
                 
{% endthumbnail %}
</div>
{% else %}
<div class="text-node">
    <p>{{node.content}}</p>
</div>
{% endif %}
{% endfor %}
</div>
</div>
{% endblock %}
<div>

articles/templates/articles/responsive_article_list.html
{% load thumbnail %}
{% load staticfiles %}
{% load social_share %}
{% for article in articles %}

    <div class="image" id="{{article.id}}">
<ul class="friend-div" id= "{{article.id}}">
<li class="fb-post">{% post_to_facebook article.url "Post to Facebook" %}</li>
<li class="twitter-post">{% post_to_twitter "Article: {{article.title}}. Check it out!" article.url "Post to Twitter" %}</l>
<li class="email-post">{% send_email article.title "Article: {{article.title}}. Check it out!" article.url "Share via email" %}</li>
</ul>
		<a href="{{ article.get_absolute_url }}">
	    {% with article.image.all as i %}
	    {% if i %}		
            {% thumbnail  i.first.image "300x300" crop="100%" as im %}
                <a href="{{ i.0.get_absolute_url }}">
                    <img src="{{im.url}}">
                </a>
            {% endthumbnail %}
	    {% else %}
              <a href="{{ article.get_absolute_url }}">
				<img src="{% static "css/global_images/default_article_img.jpg" %}">
			{% endif %}

			{% endwith %}
		</a>
        <div class="info">
            <a href="{{ article.get_absolute_url }}" class="title">
                {{ article.title }}
            </a>
			<a class="category">
                {{ article.category }}
            </a>
        </div>
<ul class="buttons">
        <li class="deleteButton" id ="{{article.id}}">
        <i class="fa fa-trash"></i>
		<div class="id-text" id="article-delete"  style="text-align: center">Delete</div>
        </li>
        <li class="articleEditButton" id ="{{article.id}}">
        <i class="fa fa-pencil-square-o"></i>
		    <div class="id-text" id="article-edit"  style="text-align: center">Edit</div>
        </li>
        <li class="friendButton" id ="{{article.id}}">
        <i class="fa my-fa-friends"></i>
		    <div class="id-text" id="article-share"  style="text-align: center">Share</div>
        </li>
		</ul>
	</div>
{% endfor %}

        <div class="delete-form-mini-container">

	<header class="popupHeader">
		<span class="header_title">Are you sure?</span>
		<span class="modal_close"><i class="fa fa-window-close"></i></span>
	</header>
            <a class="idHolder" id=""></a>

            <form class="delete-form-mini" method="post" action="">


                <div class="form-row form-last-row">
                    <button class="cancel" type="submit">Cancel</button>
                </div>

                <div class="form-row form-last-row">
                    <button class="delete-article" type="submit">Delete</button>
                </div>

            </form>
        </div>
<div class="edit-form-mini-container">
	<header class="popupHeader">
		<span class="header_title">Edit Article</span>
		<span class="edit-modal-close"><i class="fa fa-window-close"></i></span>
	</header>
           			<a class="idHolder" id=""></a>
            <form class="form-mini" method="post" action="">

				<div class="article-image"><img src=""></div>
                <div class="form-row">
                    <input id="title" type="text" name="title" value="" >
                </div>


                <div class="form-row">
                    <label>
                        <select  name="dropdown">
                            <option>Arts</option>
                            <option>Business</option>
                            <option>Education</option>
                            <option>Entertainment</option>
                            <option>Food</option>
                            <option>Health</option>
                            <option>History</option>
                            <option>Politics</option>
                            <option>Science</option>
                            <option>Society</option>
                            <option>Sports</option>
                            <option>Technology</option>
                            <option>Travel</option>
                            <option>Miscellaneous</option>
                        </select>
                    </label>
                </div>


                <div class="form-row form-last-row">

                    <button id="editArticleSubmit" type="submit">Submit</button>
                </div>

            </form>
        </div>



<div class="friend-form-mini-container">

	<header class="popupHeader">
		<span class="header_title">Share This Now!</span>
		<span class="friend-modal-close"><i class="fa fa-window-close" aria-hidden="true"></i></span>
	</header>
           <a class="idHolder" id=""></a>

            <form class="friend-form-mini" method="post" action="#">
				<div class="item-image"><img src=""></div>


               <div class="form-row form-last-row">

                    <a class="friend-button" id="fb" href=""><i class="fa my-fa-zuck"></i><span>Post to Facebook</span></a>
                </div>

               <div class="form-row form-last-row">
                    <a class="friend-button" id="twitter" href =""><i class="fa my-fa-bird" aria-hidden="true"></i><span>Post to Twitter</span></a>
                </div>
               <div class="form-row form-last-row">
                    <a class="friend-button" id="email" href=""><i class="fa fa-envelope" aria-hidden="true"></i><span>Share via Email</span></a>
                </div>
               <div class="form-row form-last-row">
                    <a class="friend-button"><div class="media-shelf-icon"></div><span>Share via MediaShelf</span></a>
                </div>
        </form>
    </div>